force-app/main/fat/objects/TriggerObserver__mdt/TriggerObserver__mdt.object-meta.xml
<CustomObject>
    <label>TriggerObserver</label>
    <pluralLabel>TriggerObservers</pluralLabel>
</CustomObject>

force-app/main/fat/objects/TriggerObserver__mdt/fields/AfterDelete__c.field-meta.xml
<CustomField>
    <fullName>AfterDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/fat/objects/TriggerObserver__mdt/fields/AfterInsert__c.field-meta.xml
<CustomField>
    <fullName>AfterInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/fat/objects/TriggerObserver__mdt/fields/AfterUndelete__c.field-meta.xml
<CustomField>
    <fullName>AfterUndelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Undelete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/fat/objects/TriggerObserver__mdt/fields/AfterUpdate__c.field-meta.xml
<CustomField>
    <fullName>AfterUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/fat/objects/TriggerObserver__mdt/fields/ApexClass__c.field-meta.xml
<CustomField>
    <fullName>ApexClass__c</fullName>
    <label>Apex Class</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/fat/classes/CommonTriggerUtils.cls
/**
 * @name CommonTriggerUtils.cls
 * @description utilities for commonTrigger
 */
public without sharing class CommonTriggerUtils {
  // Logger Variable
  private static final CommonLogger logger = CommonLogger.getInstance();

  /**
   * @name fetchTriggerObserver
   * @description fetch TriggerObserver
   */
  public static ITriggerObserver fetchTriggerObserver(Type apexClass) {
    logger.setClassName('CommonTriggerUtils');
    logger.setMethodName('fetchTriggerObserver');
    logger.stackDebugLog(LoggingLevel.FINE, '-');

    if (null == apexClass) {
      return null;
    }

    return (ITriggerObserver) apexClass.newInstance();
  }

  /**
   * @name addActiveTriggerOperations
   * @description add some active TriggerOperations
   */
  public static List<TriggerOperation> addActiveTriggerOperations(
    TriggerObserver__mdt triggerObserver
  ) {
    logger.setClassName('CommonTriggerUtils');
    logger.setMethodName('addActiveTriggerOperations');
    logger.stackDebugLog(LoggingLevel.DEBUG, triggerObserver.ApexClass__c);

    if (!triggerObserver.Active__c) {
      return null;
    }

    List<TriggerOperation> activeTriggerOperation = new List<TriggerOperation>();

    if (triggerObserver.BeforeInsert__c) {
      activeTriggerOperation.add(TriggerOperation.BEFORE_INSERT);
    }

    if (triggerObserver.BeforeUpdate__c) {
      activeTriggerOperation.add(TriggerOperation.BEFORE_UPDATE);
    }

    if (triggerObserver.BeforeDelete__c) {
      activeTriggerOperation.add(TriggerOperation.BEFORE_DELETE);
    }

    if (triggerObserver.AfterInsert__c) {
      activeTriggerOperation.add(TriggerOperation.AFTER_INSERT);
    }

    if (triggerObserver.AfterUpdate__c) {
      activeTriggerOperation.add(TriggerOperation.AFTER_UPDATE);
    }

    if (triggerObserver.AfterDelete__c) {
      activeTriggerOperation.add(TriggerOperation.AFTER_DELETE);
    }

    if (triggerObserver.AfterUndelete__c) {
      activeTriggerOperation.add(TriggerOperation.AFTER_UNDELETE);
    }

    if (triggerObserver.TestOnly__c) {
      return null;
    }

    logger.setClassName('CommonTriggerUtils');
    logger.setMethodName('addActiveTriggerOperations');
    logger.stackDebugLog(LoggingLevel.DEBUG, activeTriggerOperation);
    return activeTriggerOperation;
  }
}