force-app/main/fat/objects/FAT_LoggerEvent__e/FAT_LoggerEvent__e.object-meta.xml
<CustomObject>
    <label>FAT_LoggerEvent</label>
    <pluralLabel>FAT_LoggerEvents</pluralLabel>
</CustomObject>

force-app-fat/main/fat/objects/FAT_LoggerEvent__e/fields/Logger__c.field-meta.xml
<CustomField>
    <fullName>Logger__c</fullName>
    <label>Logger</label>
    <length>30000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/fat/objects/Logger__c/Logger__c.object-meta.xml
<CustomObject>
    <label>Logger</label>
    <nameField>
        <label>Logger ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app-fat/main/fat/classes/FAT_LoggerEventTriggerService.cls
/**
 * @name FAT_LoggerEventTriggerService.cls
 * @description service for LoggerEventTrigger
 */
public without sharing class FAT_LoggerEventTriggerService {
  /**
   * @description fetch all debugLogs
   */
  public static void fetchDebugLogs() {
    List<FAT_LoggerEvent__e> events = (List<FAT_LoggerEvent__e>) Trigger.new;
    for (FAT_LoggerEvent__e event : events) {
      FAT_CommonLogger logger = (FAT_CommonLogger) JSON.deserialize(
        event.Logger__c,
        FAT_CommonLogger.class
      );
      logger.fetch();
    }
  }
}